version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'fivos_thesis_app'
    ports: 
      - "9000:80"
    volumes: 
      - ./:/var/www/html
  db:
    image: mariadb
    restart: always
    ports:
      - "3123:3306"
    environment:
      MYSQL_DATABASE: 'fivos_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql